# Limit the number of codgen units to 1 to work around an issue where the linker fails to find the
# symbols for selectors across object files. Marking the symbols as `.globl` with or without
# `.private_extern` has no effect. Tracked by Issue #1.

[profile.bench]
codegen-units = 1

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1

[profile.test]
codegen-units = 1
