name: CI

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]

jobs:
  apple-darwin-check:
    name: ${{ format('Check {0}-[aarch64, x86_64]-apple-darwin', matrix.toolchain) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup self update
      - name: ${{ format('rustup install {0}', matrix.toolchain) }}
        run: |
          rustup install ${{ matrix.toolchain }} && \
          rustup default ${{ matrix.toolchain }}
      - run: |
          rustup target add aarch64-apple-darwin && \
          rustup target add x86_64-apple-darwin
      - run: cargo fetch
      - run: cargo check --target aarch64-apple-darwin
      - run: cargo check --target aarch64-apple-darwin --no-default-features
      - run: cargo check --target x86_64-apple-darwin
      - run: cargo check --target x86_64-apple-darwin --no-default-features
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ '1.74', 'stable' ]

  apple-darwin-test:
    name: Test stable-x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustup self update
        run: |
          brew update && \
          brew install rustup
      - name: rustup install stable
        run: |
          rustup install stable && \
          rustup default stable
      - run: cargo fetch
      - run: cargo test

  dispatch_once_inline_fastpath:
    name: Test dispatch without dispatch_once_inline_fastpath feature
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustup self update
        run: |
          brew update && \
          brew install rustup
      - name: rustup install stable
        run: |
          rustup install stable && \
          rustup default stable
      - run: cargo fetch
      - name: cargo test --package dispatch
        run: NO_DISPATCH_ONCE_INLINE_FASTPATH=1 cargo test --package dispatch

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup self update
      - run: rustup install stable
      - run: |
          rustup target add aarch64-apple-darwin && \
          rustup target add x86_64-apple-darwin
      - run: cargo fetch
      - run: cargo clippy --target aarch64-apple-darwin --all-targets -- --deny warnings
      - run: cargo clippy --target aarch64-apple-darwin --all-targets --no-default-features -- --deny warnings
      - run: cargo clippy --target x86_64-apple-darwin --all-targets -- --deny warnings
      - run: cargo clippy --target x86_64-apple-darwin --all-targets --no-default-features -- --deny warnings
